wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1666290070.433113
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.13.4
      8:
      - 5
batch_size:
  desc: null
  value: 10
checkpoint_dir:
  desc: null
  value: /home/travail/Code/LSTM2/checkpoint
dataset:
  desc: null
  value: HGD
dataset_path:
  desc: null
  value: /home/travail/Dataset/ndrczc35bt-1
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.3
gpu_num:
  desc: null
  value: '0'
learning_rate:
  desc: null
  value: 0.0001
num_classes:
  desc: null
  value: 29
num_epochs:
  desc: null
  value: 100
num_workers:
  desc: null
  value: 1
test_every:
  desc: null
  value: 1000
