# hardware
device: 'cuda'
gpu_num: '0'
num_workers: 1

# seed
seed: 0

# learning parameters
batch_size: 10
num_epochs: 20
learning_rate: 0.0001
test_every: 2000
dropout : 0.3

# network parameters
name: 'classic_cobotic_20s_v2'
num_classes: 10
depth: True
test_subject: 2
 
# Data settings
dataset : 'CHD'
dataset_path: '/store/travail/data_sorted'
data_augmentation: False
data_aug_parameter: 
    noise_factor: 0.2
    nb_black_boxes: 10
    rotation_max: 30
    black_boxes_size: 8
    resol: 1

# directories
checkpoint_dir: '/store/travail/checkpoint'
results_dir: '/store/travail/Results.json'